- appveyor.yml
Adding nodejs 0.12 and 8 to the appveyor matrix
> test: additional nodejs versions on appveyor

- lib/formats/dotnet-cli-parser.js
- test/stubs/dotnet_project/expected.json
- test/stubs/dummy_project_2/expected.json
fixes where default version is 0.0.0, but plugin happens to find manifest version - usage wasn't universal
now it is
includes updated tests
> fix: use version from manifest

- lib/index.js
- lib/proj-parser.js
- package.json
- test/csproj.test.js
- test/stubs/dotnet_2/dotnet_2.csproj
- test/stubs/dotnet_p_g/dotnet_p_g.csproj
- test/stubs/dotnet_project/dotnet_project.csproj
- test/stubs/dummy_project_2/dummy_project_2.csproj
- test/stubs/packages_dir/only_jquery/only_jquery.csproj
- test/stubs/packages_dir/only_jquery_but_wrong_version/only_jquery_but_wrong_version.csproj
- test/stubs/packages_dir/only_momentjs/only_moment.csproj
- test/stubs/stubs.csproj
- test/stubs/target_framework/csproj_multiple/csproj_multiple.csproj
- test/stubs/target_framework/csproj_multiple/expected.json
- test/stubs/target_framework/csproj_multiple/obj/project.assets.json
- test/stubs/target_framework/no_csproj/no_csproj.vbproj
- test/stubs/target_framework/no_csproj/obj/project.assets.json
- test/stubs/target_framework/no_target_framework/no_target_framework.csproj
- test/stubs/target_framework/no_target_framework/obj/project.assets.json
- test/stubs/target_framework/no_target_valid_framework/no_target_valid_framework.csproj
- test/stubs/target_framework/no_target_valid_framework/obj/project.assets.json
Added a dependency on the csproj file for the plugin to run properly. Currently it terminates if the version of the .NET framework is unsupported or we can't find it (along with a helpful error//debug statement)
In the future the version will be used to determine the correct dependencies to pull from the packages nuspec files in case of an older .NET framework project.
Most of the file additions in this PR are .csproj files that were needed for the tests to pass.
> feat: check csproj version

- lib/index.js
- package.json
- test/paket.test.js
- test/stubs/paket-missing-lock/paket.dependencies
Fixes issue where we set the `--file` flag from a different directory (`--file='./path/to/file.txt`) and the lock file was not found in the directory (`.`)
> fix: locate lock file relative to dependencies file

- lib/nuget-parser/packages-config-parser.js
- test/parse-packages-config-no-deps.test.js
- test/stubs/packages-config-no-deps/nodeps.csproj
- test/stubs/packages-config-no-deps/packages.config
when testing against a packages.config file that has no deps we got an error stating that
we cannot do forEach on undefined, this PR fixes that.
> fix: make sure that the projects const is iteratable

- lib/nuget-parser/csproj-parser.js
- test/csproj.test.js
- test/stubs/target_framework/no_csproj/obj/project.assets.json
Large nuget projects might not have their csproj file next to their obj/project.assets.json file. The paths to each of the files is listed in a properties file that we don't parse yet. Since we don't require the target framework from the csproj, yet, we can stop failing if we can't find the csproj where we expect it. This PR allows such projects to succeed when sending --file=path/to/project.assets.json flag. 
https://github.com/snyk/snyk-nuget-plugin/issues/41
> fix: succeed even if csproj not found in manifest file path

- lib/nuget-parser/framework.ts
- test/parse-dotnet-cli.test.ts
- test/repositories-config-packages.test.ts
- test/stubs/packages-config-net4/packages.config
Add a hack to handle `net4` target framework. 
It's a weird thing, but supported by Nuget Design. [NuGet.Home#1371](https://github.com/NuGet/Home/issues/1371)
> fix: support net4 as a target framework

- package.json
Bump to use latest parser version
> feat: use dotnet-deps-parser 4.5.2

- lib/nuget-parser/nuspec-parser.ts
- package.json
- tsconfig.json
They've made significant typing changes in this version, which we have to handle in two places.
Putting `dom` in `lib: []` is less horrible than casting away the types entirely, I believe. Elsewhere this version compiles fine, because `lib` defaults to containing `dom`.
`string` is equivalent to `text`, but `text` is the documented one.
> feat: upgrade jszip

- package.json
Following similar PRs, we want to get rid of our forked lodash in the dependency tree
HAMMER-99
> fix: update dotnet-deps-parser to use upstream lodash

- lib/index.ts
- lib/nuget-parser/index.ts
- test/parse-with-project-name-prefix.test.ts
Adds optional `--project-name-prefix` flag to CLI for this plugin, which allows the user to pass in a string which is prepended on to the root name (e.g. `--project-name-prefix=my-prefix/` -> `my-prefix/packages.config`. This is intended to fix several instances we've seen where a user's manifest in one project is overwritten by a similarly-named one in another; this is because we use Node's path.basename for dep tree naming, which strips out everything but the name of the file itself.
> feat: add optional project-name-prefix flag

- lib/nuget-parser/csproj-parser.ts
Without early returns after a `resolve()` or `reject()`, while the promise will fulfil, the code below it will continue to execute. Some customers were seeing "file not found" in their debug logs despite it existing. That was confusing them (and us). This is probably why.
The diff here looks complicated on GitHub due to whitespace/indent changes. All I've done is switch the `if(file)` to `if(!file)` and added `return` after the first `resolve` and  the `reject`. The diff should look better locally.
> fix: return early after fulfilling promise

- .gitignore
- lib/nuget-parser/dotnet-framework-parser.ts
- lib/nuget-parser/nuspec-parser.ts
- lib/nuget-parser/types.ts
- test/parseNuspec-no-dependencies.spec.ts
The current code does not check for when there is either not metadata or the metadata has no dependencies. We believe this is the reason for a customer getting the following error - TypeError: Cannot read property 'forEach' of undefined. This pr checks for both these cases and acts accordingly. 
Should be tested on a manifest where at least one dependency has no dependencies of it's own
> chore: ensure nuspec parsing won't fail with undefined error

- test/csproj.spec.ts
This is a minor change to push parseNuspec changes previously merged. The previous merge didn't provide a new release due to incorrect commit formation
> feat: minor change to push parseNuspec changes

- lib/nuget-parser/csproj-parser.ts
- test/csproj.spec.ts
- test/stubs/target_framework/no_target_framework2/no_target_framework2.csproj
This fixes an issue where snyk parser crashes cannot read "length" of undefined, it seems to me that logic was already handling the case where targetFrameworks returns empty array, but reading the property failed.
Simple bug fix
Added unit test, but it can be manually tested as described in these Github issues: https://github.com/snyk/snyk-nuget-plugin/issues/103 https://github.com/snyk/snyk-nuget-plugin/issues/75
-
-
-
> fix: Fixes an issue where snyk csproj parser crashes when propertyGroup is missing from project file

- lib/nuget-parser/csproj-parser.ts
- lib/nuget-parser/nuspec-parser.ts
- test/parse-utf8-bom.spec.ts
- test/stubs/utf8-bom-nuspec/NUnit.nuspec
Parsing nuspec when encoded in UTF-8 with BOM throws error `Non-whitespace before first tag` which is thrown by [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js/issues/345) library. This library doesn't support scanning files with BOM character therefore we strip it. string.trim() function removes all whitespace characters including BOM
> fix: handle nuspec files with utf8 with BOM

- lib/nuget-parser/nuspec-parser.ts
- test/parseNuspec-no-dependencies.spec.ts
Remove unnecessary error throw since the business logic dictates a NOP if a dependency object is invalid
> fix: remove unnecessary error throw

- .gitignore
- lib/errors/invalid-folder-format-error.ts
- lib/nuget-parser/dependency.ts
- test/parseNuspec-no-dependencies.spec.ts
- test/unit.spec.ts
Add diagnostic code and more detailed logging for easier diagnostics of an edge-case
For NuGet cache for .Net frameworks, the folder name should be in format of [package name].[semantic version]  
Since it is pretty much framework internals, the code assumes it is always the case. This change adds some diagnostics & logging for cases where the NuGet cache folders do not adhere to such format
> fix: add diagnostic code for edge-case

- package.json
If you install this a place where `lodash` is not already installed you'll get errors.
> fix: lodash is not a dev dep, but used in prod

- lib/nuget-parser/cli/dotnet.ts
- lib/nuget-parser/cli/subprocess.ts
Same as https://github.com/snyk/snyk-go-plugin/pull/103 and https://github.com/snyk/snyk-swiftpm-plugin/pull/29
> There is a bigger architectural change in the Extensible CLI.
> The Extensible CLI spawns a network proxy (which intercepts the SSL connections) and channels all the traffic from the legacy CLI through that internal proxy. The Intention is to add support for different features like Kerberos Proxy Authentication, OS CA stores, OAuth … through the Golang based Extensible CLI to the legacy CLI. This happens by setting the proxy settings when calling the legacy CLI from within the Extensible CLI. When the legacy CLI now calls an external tool, this tool would also try to communicate through the internal proxy. Since the internal proxy intercepts SSL connections, it uses a …
> feat: [OSM-571] replacing exec with a subprocess with support for Snyk CLI V2

- .circleci/config.yml
- lib/nuget-parser/cli/dotnet.ts
- lib/nuget-parser/index.ts
- package.json
- test/cli/dotnet.spec.ts
- test/dep-graph.spec.ts
- test/helpers/temp-fixture.ts
- test/parsers/parse-packages-config.spec.ts
- test/runtime-assembly.spec.ts
Scanning projects that targets multiple frameworks was not currently supported, as supplying something like
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>Exe</OutputType>
<TargetFrameworks>net6.0;net7.0</TargetFrameworks> <----
<RuntimeIdentifier>osx-x64</RuntimeIdentifier>
</PropertyGroup>
<ItemGroup>
<PackageReference Include="NSubstitute" Version="4.3.0" />
</ItemGroup>
</Project>
```
Would, rightfully, result in something like:
```bash
error NETSDK1129: The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, you must specify the framework for the published application.
```
So we've updated the logic to handle this case.
> feat: [OSM-592] Add support multiple target frameworks for v2 logic

- .circleci/config.yml
Right now a failed image scan won't block the release.
> chore: don't release on detected vulns in image

- lib/index.ts
- lib/nuget-parser/index.ts
- lib/nuget-parser/runtime-assembly.ts
- test/fixtures/dotnetcore/dotnet_6_and_7/dotnet_6_and_7.csproj
- test/fixtures/dotnetcore/dotnet_6_and_7/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_6_and_7/obj/project.assets.json
- test/fixtures/dotnetcore/dotnet_6_and_7/program.cs
- test/parsers/parse-core-v2.spec.ts
- test/runtime-assembly.spec.ts
Following https://github.com/snyk/snyk-nuget-plugin/pull/169, this PR enables a user to define which of the defined `<TargetFrameworks>` they wish to scan, by supplying the command line argument `--target-framework`.
This PR exists for two reasons:
1. Pave the path to enabling this plugin to scan all defined `<TargetFrameworks>` automatically, or individually if the user wishes to (though only the latter works now) and
2. Enable the SCM `v2` solution to pass along a single `TargetFramework` even if multiple are defined in the manifest file, to help optimize the parallelization of the requests optimally.
> feat: [OSM-347] Enable override with `--target-framework` if specified for `v2` logic

- lib/index.ts
- lib/nuget-parser/index.ts
- lib/nuget-parser/parsers/dotnet-core-v2-parser.ts
- test/dep-graph.spec.ts
- test/parsers/parse-core-v2.spec.ts
After https://github.com/snyk/snyk-nuget-plugin/pull/172 we want to remove the optional `useRuntimeDependencies` which was never used anywhere. We were already branching out if the option `--dotnet-runtime-resolution` was specified or not, so it did not make much sense. We already have a guard in that.
We've tested this for a while and it looks stable. It was inserted as a failsafe being over-cautious, but I feel comfortable removing it again now.
This should pave the road to enable the actual implementation of what we want, the multi-result solution for multiple `<TargetFramework>`s.
> feat: [OSM-347] Return multiple results part 2: Removing stuff we never used

- lib/index.ts
- lib/nuget-parser/index.ts
- test/parsers/parse-core-v2.spec.ts
After doing a sync up with product we decided this is more consistent with the beta flag `--dotnet-runtime-resolution`.
> feat: [OSM-695] renaming `--target-framework` to `--dotnet-target-framework`

- lib/nuget-parser/csharp/nugetframeworks_parser.ts
Previous version only worked on `net7.0` specifically, this should make it more lenient.
> chore: fixed locked version bug

- lib/nuget-parser/index.ts
- lib/nuget-parser/runtime-assembly.ts
- package.json
- test/runtime-assembly.spec.ts
See [this](https://github.com/snyk/dotnet-deps-parser/pull/84).
(Everything will fail until that is merged ☝🏻 )
> fix: [OSM-699] Replace `isSupported` runtime assembly logic with shared logic from `dotnet-deps-parser`

- lib/index.ts
- lib/nuget-parser/index.ts
- lib/nuget-parser/types.ts
- test/dep-graph.spec.ts
- test/fixtures/dotnetcore/dotnet_6_and_7/expected_depgraphs.json
- test/fixtures/props/build-props/App/obj/project.assets.json
- test/parsers/parse-core-v2.spec.ts
This change hooks up the work that was done in
* https://github.com/snyk/snyk-nuget-plugin/pull/172 and
* https://github.com/snyk/snyk-nuget-plugin/pull/173 and
* https://github.com/snyk/snyk-nuget-plugin/pull/175
and finalizes the return value to be a [MultiProjectResult](https://github.com/snyk/snyk-cli-interface/blob/5379064a85628737ffd5b94b230778d62ce4d7f1/legacy/plugin.ts#L130-L135) instead of a `SingleProjectResult`.
The CLI already supports this out of the box (though I have attempted to do a small [UX improvement](https://github.com/snyk/cli/pull/4914)) - but the isolated builds version will need a slight update.
> feat: [OSM-347] Return multiple results when no specific `TargetFramework` has been specified

- lib/nuget-parser/cli/dotnet.ts
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj1/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj1/obj/project.assets.json
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj1/program.cs
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj1/proj1.csproj
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj2/obj/project.assets.json
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj2/program.cs
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj2/proj2.csproj
- test/parsers/parse-core-v2.spec.ts
The `--dotnet-runtime-resolution` logic relies on some string parsing to understand where we placed the `.dll` or `.exe` assemblies we need to identify. I did not think about local `PackageReferences` that needs to be restored in a chained order.
Thus my logic extracted the first element it found in the `stdout` log, where it should have looked for the last.
> fix: [OSM-782] Fix local `PackageReference` bug for `v2` parsing

- lib/nuget-parser/cli/dotnet.ts
The previous `v2` parsing logic did a whole bunch of over engineered magic to determine where the publish dir of the `.dll`s we need.
Just asking `dotnet restore` to define a `--output` should work a bit better 🤦🏻 .
> feat: dropping the stdout traversal stuff

- lib/nuget-parser/cli/dotnet.ts
- lib/nuget-parser/parsers/dotnet-core-v2-parser.ts
- test/runtime-assembly.spec.ts
For the `v2` parser, there were situations where the `dotnet publish` would not include all the required runtime `.dll`s in cases where a RID was not defined.
This is a part of the issue we want to solve by also passing on runtime identifiers from the customer's environment, but it's a bit of a bigger picture.
Forcing the `dotnet restore` to use the current runtime will force the published artifact to contain the required `.dll`s which we need to traverse.
* Added a test that provokes the error.
* Added a fix for the `dotnet` cli tool
> feat: [SUP-2193] Transitive dependency fixes for `v2` parsing with missing `RID`s.

- .circleci/config.yml
- test/fixtures/dotnetcore/dotnet_8/dotnet_8.csproj
- test/fixtures/dotnetcore/dotnet_8/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8/program.cs
- test/parsers/parse-core-v2.spec.ts
.NET 8 is now LTS. We've been supporting it for a while, but now we can officially move our executors and other things in the pipeline to this version.
> fix: add `net8.0` testing

- lib/nuget-parser/parsers/dotnet-core-v2-parser.ts
- test/fixtures/dotnetcore/dotnet_6/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_6_and_7/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_6_and_7/expected_depgraphs.json
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj1/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_6_no_rid/expected_depgraph.json
- test/fixtures/props/build-props/App/expected_depgraph.json
- test/parsers/parse-core-v2.spec.ts
> [They are very noisy and not particularly useful.](https://github.com/dotnet/core/issues/7568)
For our case, we are already creating the correct dependencies and their respective runtime version numbers based of our runtime resolution logic. So a dependency will already be `System.Net.Http@8.0.0` if running on .NET 8, thus removing the need for a `runtime.native.System.Net.Http@8.0.0` as well. From our investigation these runtime native dependencies are causing noise for the customers and are not of interested.
Changes: 
* Added test to reproduce the issue
* Fixed the issue in the `v2` parser
* Updated depGraph fixtures that are now no longer containing the `runtime.*` dependencies
> fix: [OSM-797] Remove `runtime.*` natives from depGraph

- lib/nuget-parser/index.ts
- lib/nuget-parser/parsers/dotnet-core-v2-parser.ts
- lib/nuget-parser/runtime-assembly.ts
- lib/nuget-parser/types.ts
- test/dep-graph.spec.ts
- test/fixtures/dotnetcore/dotnet_6_local_package_reference/proj1/expected_depgraph.json
- test/runtime-assembly.spec.ts
Thanks to the wonders of beta testing, we've found a much cleaner way to generate the same dependency graph with much less code and more accurate results. Long story short, we were relying way too much on the `assets.json` file over the `deps.json` file.
It was disclosed by a bug that introduced the wrong transitive dependency version.
There is a ton of depGraph tests, and they're all still passing. 🟢 
... except for that one which turned out to be wrong. 😑
> feat: [OSM-801] Rewrite of dependency graph generation for `v2` parser

- lib/nuget-parser/index.ts
- test/dep-graph.spec.ts
Adding a target framework as
```
<TargetFramework>net7.0-windows</TargetFramework>
```
Will render the framework name in `project.assets.json` as
```json
{
"version": 3,
"targets": {
"net7.0-windows7.0": {
"AsyncFixer/1.6.0": {
"type": "package"
},
"IDisposableAnalyzers/4.0.7": {
"type": "package"
},
(...)
```
And currently we pick up that target name verbatim as pass it along as a valid target framework. That's not the case, apparently, as the correct target framework ought to be `net7.0-windows`, which the assets file do describe in the frameworks list as a `targetAlias`:
```json
"frameworks": {
"net7.0-windows7.0": {
"targetAlias": "net7.0-windows",
"projectReferences": {
(...)
```
So this PR changes the list of targetFrameworks we work with to use the alias if detected, key name …
> fix: [OSM-887] Use `targetAlias` where present instead of raw target name

- lib/nuget-parser/parsers/packages-config-parser.ts
- test/fixtures/packages-config/malformed/packages.config
- test/inspect.spec.ts
A customer had a malformed `packages.config` that just blew up their pipeline with a traceback instead of a more graceful error.
> fix: [SUP-2195] better error handling of malformed packages.config

- lib/nuget-parser/cli/dotnet.ts
- lib/nuget-parser/index.ts
- test/fixtures/dotnetcore/dotnet_8_custom_project_and_output_path/Directory.Build.props
- test/fixtures/dotnetcore/dotnet_8_custom_project_and_output_path/nested_csproj/dotnet_8.csproj
- test/fixtures/dotnetcore/dotnet_8_custom_project_and_output_path/nested_csproj/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_custom_project_and_output_path/nested_csproj/program.cs
- test/parsers/parse-core-v2.spec.ts
You can customize the output path to something different than `obj/project.assets.json` which we have hard coded various places.
This PR changes the logic to probe `dotnet restore` about where the assets file has been written, and use that as a baseline instead.
> feat: [OSM-955] Adding support for custom `<BaseOutputPath>`

- lib/nuget-parser/cli/dotnet.ts
We're seeing very slow builds on large .NET projects when running through the cli with `--all-projects`, and there are some inconveniences in this plugin that could probably help alleviate this.
This PR:
* Removes `--no-cache` when doing `dotnet restore`. Not sure why I even added this. Think I wanted to have a clean slate guarantee.
* Drops `--output` in favor of `--property:PublishDir=<dir>` as per https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/solution-level-output-no-longer-valid#recommended-action suggestions.
The general recommendation is to drop a specified output path all together, but I don't see a trivial way of getting `dotnet` to tell me where it intends to publish by default.
> fix: [OSM-998] Performance optimization attempts

- lib/nuget-parser/index.ts
- lib/nuget-parser/parsers/dotnet-core-v2-parser.ts
If scanning multiple target frameworks, we previously would re-create the .NET code to validate said TargetFrameworks on each iteration.
This just moves it out of the loop.
> fix: [OSM-798] not generating .NET code on each TF iteration

- lib/nuget-parser/cli/dotnet.ts
- lib/nuget-parser/index.ts
This user-friendly update: https://github.com/snyk/snyk-nuget-plugin/pull/207 was a tad too friendly. Any .NET version other than 8 caused it to fail.
Though I still believe in the power of useful error messages, and the SCM solution will still benefit from this. The alternative is a weird dotnet crash with a missing `.deps` file. 
So this is the compromise.
The CCI runners are already running .NET 8 and thus tests are still passing. The negative case is a bit more cumbersome, as most fixtures targeting .NET 8 will fail with a .NET 7/6 executor.
> fix: [OSM-1718] Fix `isPublishable` error on older dotnet versions

- .circleci/config.yml
- package.json
- test/parsers/parse-core-v2.spec.smoke.ts
We had some regression tests when running against older or soon-to-be EOL'ed .NET versions. Added some some test job to run through happy paths with older .NET versions.
> feat: adding smoke tests for multiple .net versions

- lib/nuget-parser/cli/dotnet.ts
- lib/nuget-parser/index.ts
- test/fixtures/dotnetcore/dotnet_8_unpublishable/dotnet_8_unpublishable.csproj
- test/fixtures/dotnetcore/dotnet_8_unpublishable/program.cs
- test/parsers/parse-core-v2.spec.ts
the `isPublishable` was added to make better error messages for users who try to scan a project defined be not publishable.
However, this flag causes issues with older .NET versions. Will be removed until a better solution is in place.
> fix: remove isPublishable logic

- lib/nuget-parser/index.ts
- lib/nuget-parser/types.ts
- test/fixtures/dotnetcore/dotnet_8_multiple_projects_same_folder/dotnet_8_first.csproj
- test/fixtures/dotnetcore/dotnet_8_multiple_projects_same_folder/dotnet_8_second.csproj
- test/fixtures/dotnetcore/dotnet_8_multiple_projects_same_folder/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_multiple_projects_same_folder/program.cs
- test/parsers/parse-core-v2.spec.ts
We have a bug in the Improved .NET Scanning that manifests itself when `dotnet` tries to restore and/or publish inside a folder where multiple `.csproj` files exist.
Our logic just sends `dotnet` the folder to use, not the specific filename.
This PR changes that.
> fix: [OSM-1797] Fixing bug that caused a failure when running `snyk test` in a multi-project folder

- lib/nuget-parser/cli/dotnet.ts
- test/fixtures/dotnetcore/dotnet_8 with spaces in path/dotnet 8.csproj
- test/fixtures/dotnetcore/dotnet_8 with spaces in path/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8 with spaces in path/program.cs
- test/parsers/parse-core-v2.spec.smoke.ts
- test/parsers/parse-core-v2.spec.ts
The previous commit fixed the multi-project problem, but did not think about (mostly Windows) type projects with spaces. Rudimentary mistake. Fixed here.
> fix: [OSM-1797] Fixing bugs related to paths with spaces

- lib/nuget-parser/index.ts
- test/fixtures/dotnetcore/dotnet_8_local_package_reference/BaseProj.csproj
- test/fixtures/dotnetcore/dotnet_8_local_package_reference/SecondaryProj/SecondaryProj.csproj
- test/fixtures/dotnetcore/dotnet_8_local_package_reference/SecondaryProj/expected_depgraph.json
- test/parsers/parse-core-v2.spec.ts
In some cases of nested projects, if a subproject references a local one higher in path, `dotnet publish` will generate `.deps.json` files for both projects. The actual logic finds and uses the first `.deps.json` file found, even though it is not for the scanned project.
This PR fixes that bug.
Attached bellow an example of a `.bin` folder for the `SecondaryProj`, generated by `dotnet publish` were the bug can be visualised
> fix: fixed reading wrong deps.json file

- lib/index.ts
- lib/nuget-parser/index.ts
Sending user facing messages to stdout will cause issues when using the `--json` flag (the message gets displayed in the json graph and thus making it invalid). This PR uses stderr to display user facing messages.
> fix: send user messages to stderr

- lib/index.ts
- lib/nuget-parser/index.ts
Maintaining same functionality as https://github.com/snyk/snyk-nuget-plugin/pull/217 but makes the code more readable (we're not erroring out, just displaying a warn message for the user)
> fix: replacing method used for displaying messages

- lib/nuget-parser/cli/dotnet.ts
- test/fixtures/dotnetcore/dotnet_8_is_not_publishable/dotnet_8.csproj
- test/fixtures/dotnetcore/dotnet_8_is_not_publishable/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_is_not_publishable/program.cs
- test/parsers/parse-core-v2.spec.ts
.NET projects can be configured to not be publishable (test project as for example)
Improved .NET needs those projects to be publishable in order to generate the self-contained binary that has all the required runtime dependencies
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#msbuild
This PR enhances the `dotnet publish` command to overwrite `<IsPublishable>` property to be true in order to successfully scan those projects.
> fix: scan non publishable projects

- lib/nuget-parser/cli/dotnet.ts
- test/fixtures/dotnetcore/dotnet_8_publish_single_file/dotnet_8_publish_single_file.csproj
- test/fixtures/dotnetcore/dotnet_8_publish_single_file/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_publish_single_file/program.cs
- test/parsers/parse-core-v2.spec.ts
Some projects can have `<PublishSingleFile>` tuned on, this won't allow `dotnet publish` to generate the self-container binary. This PR turns that setting to false during our scan
> fix: disable PublishSingleFile during snyk scan

- lib/nuget-parser/cli/dotnet.ts
- test/fixtures/dotnetcore/dotnet_8_treat_warnings_as_errors/dotnet_8_treat_warnings_as_errors.csproj
- test/fixtures/dotnetcore/dotnet_8_treat_warnings_as_errors/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_treat_warnings_as_errors/program.cs
- test/parsers/parse-core-v2.spec.ts
Projects can have properties like `<TreatWarningsAsErrors>` and `<WarningsAsErrors>` that will make the `dotnet publish` command to fail for any encountered warning. There is no reason for us to fail the scan if dotnet detected a warning. In lots of cases those warnings are from the range: https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1901-nu1904
This PR deactivated those two settings when running `dotnet publish`
> fix:do not treat warnings as errors

- lib/nuget-parser/cli/dotnet.ts
- test/fixtures/dotnetcore/dotnet_8_with_snyk_test_property/dotnet_8_with_snyk_test_property.csproj
- test/fixtures/dotnetcore/dotnet_8_with_snyk_test_property/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_with_snyk_test_property/program.cs
- test/parsers/parse-core-v2.spec.ts
Adds a `SnykTest` property to the dotnet env when `dotnet publish` is running. This will allow customers to conditionally activate/deactivate specific dotnet properties when snyk is scanning their manifest files
More details here: https://github.com/snyk/snyk-nuget-plugin/pull/222
> fix: add snyk test build property

- lib/nuget-parser/cli/dotnet.ts
Same as https://github.com/snyk/snyk-nuget-plugin/pull/223 but for `dotnet restore`
> fix: do not treat warnings as errors on restore

- lib/nuget-parser/parsers/dotnet-core-v2-parser.ts
- test/fixtures/dotnetcore/dotnet_8_with_package_id_property/dotnet_8_with_package_id_property.csproj
- test/fixtures/dotnetcore/dotnet_8_with_package_id_property/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_with_package_id_property/program.cs
- test/parsers/parse-core-v2.spec.ts
Dotnet is not consistent with project names, this PR adds a default to find the target using the .csproj filename.
<PackageId> property overrides most of the naming when restoring, but when publishing, the self-contained binary will have the actual filename as the target.
> fix: default to filename as proj name for target

- .circleci/config.yml
- lib/nuget-parser/cli/dotnet.ts
- tsconfig.json
adds version 9 to the smoke tests
and a workaround until https://github.com/dotnet/sdk/issues/44610 gets fixed, hopefully on the next dotnet sdk release
> fix: adds dotnet 9 to smoke tests and removes progress indicators

- lib/nuget-parser/parsers/dotnet-core-v2-parser.ts
- test/fixtures/dotnetcore/dotnet_8_transitive_false_positive/FirstProject/dotnet_8_transitive_false_positive.csproj
- test/fixtures/dotnetcore/dotnet_8_transitive_false_positive/FirstProject/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_transitive_false_positive/FirstProject/program.cs
- test/fixtures/dotnetcore/dotnet_8_transitive_false_positive/SecondProject/dotnet_8_second_project.csproj
- test/fixtures/dotnetcore/dotnet_8_transitive_false_positive/SecondProject/program.cs
- test/parsers/parse-core-v2.spec.ts
Imported projects (from NuGet/private NuGet Feeds) can also influence the version of the runtime dependency. 
The correct NuGet version is hoisted from the inner projects to the main self-container binary as an empty object.
This PR will take them into account.
> fix: false positives from transitive deps

- lib/nuget-parser/cli/dotnet.ts
- test/fixtures/dotnetcore/dotnet_8_duplicate_publish_output_files/FirstProject/appsettings.json
- test/fixtures/dotnetcore/dotnet_8_duplicate_publish_output_files/FirstProject/dotnet_8_duplicate_publish_output.csproj
- test/fixtures/dotnetcore/dotnet_8_duplicate_publish_output_files/FirstProject/expected_depgraph.json
- test/fixtures/dotnetcore/dotnet_8_duplicate_publish_output_files/SecondProject/appsettings.json
- test/fixtures/dotnetcore/dotnet_8_duplicate_publish_output_files/SecondProject/dotnet_8_duplicate_publish_output_second.csproj
- test/parsers/parse-core-v2.spec.ts
some projects can be configured to always output files like appsettings.json to the output directory, and that is not a problem for normal publish actions, but we are publishing to a temp directory which will result in a NETSDK1152 error
disabling that error as those files are not relevant to the deps discovery
> fix: disable error on duplicate output files

- lib/nuget-parser/parsers/dotnet-core-v3-parser.ts
- test/fixtures/dotnetcore/dotnet-8-windows-targeting/Program.cs
- test/fixtures/dotnetcore/dotnet-8-windows-targeting/dotnet_8_windows_targeting.csproj
- test/fixtures/dotnetcore/dotnet-8-windows-targeting/expected_depgraph-v2.json
- test/fixtures/dotnetcore/dotnet-8-windows-targeting/expected_depgraph-v3.json
- test/fixtures/dotnetcore/dotnet-8-windows-targeting/expected_depgraph.json
- test/parsers/parse-core-v2.spec.ts
`-windows` target frameworks will have a different representation inside .targets in assets.json
> fix: windows targeting in v3

- lib/nuget-parser/parsers/dotnet-core-v3-parser.ts
- test/fixtures/dotnetcore/dotnet_6_specific_windows_build/Program.cs
- test/fixtures/dotnetcore/dotnet_6_specific_windows_build/dotnet_6_specific_windows_build.csproj
- test/fixtures/dotnetcore/dotnet_6_specific_windows_build/expected_depgraph-v2.json
- test/fixtures/dotnetcore/dotnet_6_specific_windows_build/expected_depgraph-v3.json
- test/fixtures/dotnetcore/dotnet_6_specific_windows_build/expected_depgraph.json
- test/parsers/parse-core-v2.spec.ts
Allow matching the target framework as a prefix or a superstring of entries in project.assets.json
CLI tests
The scenario i'm fixing was added as a test case to the suite
https://snyksec.atlassian.net/browse/OSM-2905
> feat: [OSM-2905] Handle target framework partially matching project.assets.json

- lib/nuget-parser/cli/dotnet.ts
set MSBuildEnableWorkloadResolver to true when running the restore command. This is to ensure the command works even when the setting is off when set in the csproj or prop files.
> fix: set MSBuildEnableWorkloadResolver so we can always run the restore command

- lib/nuget-parser/index.ts
- lib/nuget-parser/parsers/dotnet-core-v3-parser.ts
- lib/nuget-parser/types.ts
- test/fixtures/dotnetcore/netcoreapp31/expected_depgraph-v3.json
- test/fixtures/dotnetcore/netstandard21_no_assemply_overrides/expected_depgraph-v3.json
- test/fixtures/dotnetcore/netstandard21_no_assemply_overrides/netstandard21_no_assemply_overrides.csproj
- test/parsers/parse-core-v2.spec.ts
Optimised the `getResultsWithoutPublish()` function to skip expensive runtime assembly override processing for .NET Standard and .NET Code App projects, since these overrides should be never used for netstandard or netcoreapp target frameworks.
**No functional changes** - runtime assembly overrides still work correctly for .NET Core/.NET 5+ projects where they're actually used.
> fix: exclude assemblies for nestandard and netcoreapp for nuget v3
