snyk/snyk-nuget-plugin

lib/dependency.js, lib/index.js, lib/nuspec-parser.js, test/parse-without-traverse.test.js, test/stubs/dummy_project_1/dummy_project_1/expected_csproj.json, test/stubs/dummy_project_1/dummy_project_1/expected_pkgcfg.json
the unified list is generated both from manifest and installed packages found on disk under packages folder
=> fix: reporting unified list of packages

lib/index.js, test/parse-with-traverse.test.js, test/parse-without-traverse.test.js
Moved the plugin position in the payload in order to be detectable by snyk monitor command
=> feat: supporting snyk monitor

lib/formats/dotnet-cli-parser.js, test/parse-dotnet-cli-2-with_duplicate_deps.test.js, test/parse-dotnet-cli-2.test.js, test/parse-dotnet-cli-p-g.test.js, test/stubs/dotnet_2/expected.json, test/stubs/dotnet_2/obj/project.assets.json, test/stubs/dotnet_p_g/expected.json, test/stubs/dotnet_p_g/obj/project.assets.json, test/stubs/dotnet_project/expected.json
this is not ready. it is intended that the tests show what problem this solution creates. i'll elaborate later
=> fix: take major version

lib/dependency.js, lib/formats/dotnet-core-parser.js, lib/index.js, lib/nuspec-parser.js, test/parse-without-traverse.test.js, test/stubs/dotnet_2/expected.json, test/stubs/dotnet_p_g/expected.json, test/stubs/dotnet_project/expected.json, test/stubs/dummy_project_1/dummy_project_1/expected_csproj.json, test/stubs/dummy_project_1/dummy_project_1/expected_pkgcfg.json, test/stubs/dummy_project_2/expected.json, test/stubs/packages_dir/only_jquery/expected.json, test/stubs/packages_dir/only_jquery_but_wrong_version/expected.json, test/stubs/packages_dir/only_momentjs/expected.json
as the backend doesn't need it anymore,
and it reduces the result json size by 3
=> feat: don't include `from` arrays in tree

lib/dotnet-parser.js, lib/index.js, package.json, test/paket.test.js, test/stubs/simple-paket/paket.dependencies, test/stubs/simple-paket/paket.lock
Refactor nuget parsing and add `paket` support in the plugin
=> Feat: add paket parsing

package.json
Bump snyk-paket-parser to `1.4.1`.
=> fix: bump snyk-paket-parser

lib/dotnet-parser.js, lib/index.js, lib/proj-parser.js, test/stubs/packages_dir/only_jquery/expected.json, test/stubs/packages_dir/only_jquery_but_wrong_version/expected.json, test/stubs/packages_dir/only_momentjs/expected.json
Passes on the target framework detected by the plugin.
=> feat: pass on dotnet runtime framework to be monitored

.eslintrc, test/parse-core-project-name-in-assets-file.test.js
Release csproj naming improvements when scanning .sln files & increase line length limit form 80 => 100
=> feat: Release improved csproj naming and linting updates

package.json
Updates snyk-paket-parser version. New snyk-parser-version supports parsing options in `nuget` dependency string
=> Update snyk-paket-parser version

lib/nuget-parser/dotnet-core-parser.ts, test/csproj.test.ts, test/stubs/target_framework/no-dependencies/csproj_no_deps.csproj, test/stubs/target_framework/no-dependencies/obj/project.assets.json
Following https://github.com/snyk/snyk/issues/832, we fail if there are not dependencies in the csproj
=> fix: don't fail when there are no dependencies

.gitignore, package.json
Introduce a new props parsing function that is
for now unused
=> feat: bump parser

package.json
- Bump parser to skip more unresolved deps, unused in CLI no functional impact
=> feat: bump parser, no functional impact

package.json
New functionality to use props that is for now unused, so no functional changes
=> feat: bump parser, no functional changes

.gitignore, package.json, tsconfig.json
Upgrade all the things. Specifically, the upgrade of `jszip` removes the dependency on `core-js`.
=> feat: bumps

lib/nuget-parser/csproj-parser.ts, lib/nuget-parser/dotnet-core-parser.ts, lib/nuget-parser/index.ts, lib/nuget-parser/nuspec-parser.ts, package.json, test/csproj.test.ts
Remove lodash dependency and replace with native Javascript
=> feat: drop lodash

.eslintrc.js, .prettierrc.json, lib/errors/index.ts, lib/index.ts, lib/nuget-parser/csproj-parser.ts, lib/nuget-parser/dependency.ts, lib/nuget-parser/dotnet-core-parser.ts, lib/nuget-parser/dotnet-framework-parser.ts, lib/nuget-parser/framework.ts, lib/nuget-parser/index.ts, lib/nuget-parser/nuspec-parser.ts, lib/nuget-parser/packages-config-parser.ts, lib/nuget-parser/project-json-parser.ts, package.json
Add code formatting to the plugin. We use it across Snyk, so this helps keep things consistent and reduces time spent on code style discussions
=> chore: add code formatting

package.json
Updating jszip package to mitigate a vulnerability
=> fix: update jszip package

lib/nuget-parser/dependency.ts, lib/nuget-parser/nuspec-parser.ts, package.json, tsconfig.json
In this PR, I fixed the broken CI by upgrading the typescript form 3.x to 4.x
I changed the following:
- upgraded to the safe combination of `typescript`, `jest` and `ts-jest` using [snyk-docker-plugin](https://github.com/snyk/snyk-docker-plugin) repo versions
- changes for some new typescript compiler errors
I would start with `package.json` file
I think that our smoke tests in the snyk CLI should be enough
I need to publish a new version of this package with a fix of an edge case problem with large `dotnetcore` projects.
To do that, I first fixed the CI.
=> fix: upgrade typescript

.github/CODEOWNERS
Update code owners to current supporting team
=> fix: code owners

.circleci/config.yml
=> fix: CIrcleCI in master

.circleci/config.yml
=> fix: fix ci

.github/workflows/broken-link-check.yml
add broken link github action to PR's
=> feat: add broken link github action

package.json
Updating `dotnet-deps-parser` for Snyk-on-Snyk
=> Update `dotnet-deps-parser` dependency

lib/nuget-parser/nuspec-parser.ts, package.json
Based off of `drop-tap`, so merge that first.
=> fix: bump everything

.circleci/config.yml, .github/CONTRIBUTING.md, README.md
`master` have now been renamed `main`.
=> fix: master -> main

lib/index.ts
=> feat: adding a warning message when running this with runtime resolution

.circleci/config.yml
Pipeline runs tests on main branch and the release step requires scan and tests to pass.
- [Jira ticket OSM-632](https://snyksec.atlassian.net/browse/OSM-632)
=> chore: pipeline test on main and release fail

lib/nuget-parser/parsers/dotnet-core-v2-parser.ts, test/dep-graph.spec.ts
I'd erroneously relied on the fact that the version defined in `project.assets.json` would be the same as the package name used in `project.deps.json` after a successful `publish`. This was not the case.
`dotnet` does [version normalization](https://github.com/NuGet/NuGet.Client/blob/08e07ea13985fb259b35b9ce90fd99339f0fdef2/src/NuGet.Core/NuGet.Versioning/NuGetVersion.cs#L148) when doing `dotnet restore`, but the same logic is not applied when doing `dotnet publish`.
I've not found another place where `dotnet` stores the non-normalized version for easy access, so I've changed the logic that looks for this package away from explicitly looking for a full version, as previous:
https://github.com/snyk/snyk-nuget-plugin/blob/675b208d373d7c7dce2f214929043e641c93b52d/lib/nuget-parser/parsers/dotn …
=> fix: [OSM-887] Fixing depGraph build error on version definition in `.props`

lib/index.ts, lib/nuget-parser/index.ts
https://docs.snyk.io/supported-languages-package-managers-and-frameworks/.net/improved-.net-scanning#supported-.net-versions
=> fix: update supported net version

lib/index.ts
updated the message body and the link
=> fix: update warning message for improved net

lib/nuget-parser/cli/dotnet.ts, test/cli/dotnet.spec.ts
seeing the args makes it easier to understand what went wrong with dotnet commands
=> fix: increase logging for dotnet commands
